[SERVICE]
    Flush         5
    Log_Level     warn
    Parsers_File  /fluent-bit/etc/parsers.conf

[FILTER]
    Name          record_modifier
    Match         *
    Record        service hezo-backend
    Record        environment production

[OUTPUT]
    Name          loki
    Match         *
    Host          ${OBS_EC2_PRIVATE_IP}
    Port          3100
    Labels        job=ecs,service=hezo-backend
    Remove_keys   container_id,ecs_task_arn
    Auto_Kubernetes_Labels off
